CREATE TABLE csj_data (
                            date varchar(16) not null comment '日期 yyyy-MM-dd 格式',
                          time_zone VARCHAR(255) NOT NULL COMMENT '时区',
                          currency VARCHAR(255) NOT NULL COMMENT '币种单位',
                          region VARCHAR(255) NOT NULL COMMENT '国家或地区代码，同 ISO3166-1 标准，使用两位字母编码。',
                          app_id INT NOT NULL COMMENT '应用id',
                          app_name VARCHAR(255) NOT NULL COMMENT '应用名称',
                          ad_slot_id INT NOT NULL COMMENT '代码位id',
                          ad_slot_type INT NOT NULL COMMENT '1（信息流）、2（Banner）、3（开屏）、4（插屏）、5（激励视频）、6（全屏视频）、7（Draw信息流）、8（贴片）、9（新插屏广告）',
                          ad_slot_type_v2 INT NOT NULL COMMENT '1（信息流）、2（Banner）、3（开屏）、4（插屏）、5（激励视频）、6（全屏视频）、7（Draw信息流）、8（贴片）、91（新插屏全屏）、92（新插屏半屏）',
                          request INT NOT NULL COMMENT '广告请求量',
                          return_count INT NOT NULL COMMENT '物料返回',
                          fill_rate FLOAT NOT NULL COMMENT '填充率',
                          show INT NOT NULL COMMENT '展示量',
                          click INT NOT NULL COMMENT '点击量',
                          click_rate FLOAT NOT NULL COMMENT '点击率',
                          revenue FLOAT NOT NULL COMMENT '预估收益（T日）真实收益(T-1日10点后-国内；T-1日14点以后-海外）',
                          ecpm FLOAT NOT NULL COMMENT '预估ecpm',
                          package_name VARCHAR(255) NOT NULL COMMENT '包名',
                          use_mediation INT NOT NULL COMMENT '是否使用穿山甲聚合. 0 (否) 、1 (是)',
                          bidding_type INT NOT NULL COMMENT '竞价类型. 0 (标准) 、1 (客户端竞价) 、2 (服务端竞价)',
                          ad_request INT NOT NULL COMMENT '物料请求量',
                          response INT NOT NULL COMMENT '广告返回量',
                          ad_fill_rate FLOAT NOT NULL COMMENT '物料填充率=物料返回量/物料请求量',
                          ad_impression_rate FLOAT NOT NULL COMMENT '物料展示率=展示量/物料返回量',
                          PRIMARY KEY (ad_slot_id, date) -- 假设 ad_slot_id 和 date 组合在数据库中是唯一的
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='穿山甲数据';
